### ISSUE TITLE
Syntax error when run it in HPC

### ISSUE THREAD

**Issue by laurelgui** [jin-wash-u/HPV-EM#1]
Hi, I was trying to run HPV-EM in the HPC terminal. Yet I received a series of syntax error, such as:

$ python HPV-EM.py -s ../GRCh38.100 ../Data/xxx_1.fq ../Data/xxx_2.fq
  File "HPV-EM.py", line 31
    except subp.CalledProcessError, e:
                                  ^
SyntaxError: invalid syntax

also error shown for print, etc. I am running with python/3.7.0. How could I address this issue? Thanks!

**Comment by jin-wash-u** [comment]
It is due to different python versions.

We will address this compatibility issue in the coming updates.

**Comment by mjinkm** [comment]
Hi laurelgui,

HPV-EM has been updated so it can be run with Python 3+ without errors.
